/* 
This code was generated by the resgen-ts tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated 
*/

export interface IStrings { 
	/** first name here */
	readonly fName: string;
	/** last name here */
	readonly lName: string;
	/**  */
	readonly mName: string; 
}