/* 
This code was generated by the resgen-ts tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated 
*/

import {IStrings} from './iStrings.res'; 

export class Strings implements IStrings {
	/** first name here */
	public get fName(): string {
		return "First Name";
	}

	/** last name here */
	public get lName(): string {
		return "Last Name";
	}

	/**  */
	public get mName(): string {
		return "Middle Name";
	}
}