/* 
This code was generated by the resgen-ts tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated 
*/

export interface IStringResources { 
	/** Please enter your first name */
	readonly fNameDesc: string; 
}