/* 
This code was generated by the resgen-ts tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated 
*/

import {IStringResources} from './iStringResources.res'; 

export class StringResources implements IStringResources {
	/** Please enter your first name */
	public get fNameDesc(): string {
		return "First Name";
	}
}